// @generated by scripts/generate-renderer-capability-contract.mjs
// Do not edit by hand. Regenerate from the current TypeScript unions.

pub(crate) const GENERATED_RENDERER_CAPABILITY_CONTRACT_SHA256: &str =
    "2c38e530608e186e8559392c415e7599990a96a22da55250de0274bafa1cc840";

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum GeneratedEventDisposition {
    PresentationOnly,
    Recoverable,
    TurnFatal,
    ProtocolFatal,
}

#[allow(dead_code)]
pub(crate) const GENERATED_STREAM_EVENT_POLICIES: &[(&str, GeneratedEventDisposition)] = &[
    ("content_block_delta", GeneratedEventDisposition::TurnFatal),
    ("content_block_start", GeneratedEventDisposition::TurnFatal),
    ("content_block_stop", GeneratedEventDisposition::TurnFatal),
    ("error", GeneratedEventDisposition::TurnFatal),
    ("message_delta", GeneratedEventDisposition::TurnFatal),
    ("message_start", GeneratedEventDisposition::TurnFatal),
    ("message_stop", GeneratedEventDisposition::TurnFatal),
    ("ping", GeneratedEventDisposition::PresentationOnly),
    ("sources", GeneratedEventDisposition::PresentationOnly),
];

#[allow(dead_code)]
pub(crate) fn generated_stream_event_disposition(
    event_type: &str,
) -> Option<GeneratedEventDisposition> {
    GENERATED_STREAM_EVENT_POLICIES
        .iter()
        .find_map(|(known, disposition)| (*known == event_type).then_some(*disposition))
}

pub(crate) const GENERATED_DIRECT_MESSAGE_TYPES: &[&str] = &[
    "assistant",
    "attachment",
    "progress",
    "stream_event",
    "stream_request_start",
    "system",
    "tombstone",
    "tool_use_summary",
    "user",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_DIRECT_SYSTEM_SUBTYPES: &[&str] = &[
    "agents_killed",
    "api_error",
    "api_metrics",
    "away_summary",
    "command_input",
    "compact_boundary",
    "file_snapshot",
    "informational",
    "local_command",
    "memory_saved",
    "microcompact_boundary",
    "permission_retry",
    "scheduled_task_fire",
    "stop_hook_summary",
    "thinking",
    "turn_duration",
];

pub(crate) const GENERATED_DIRECT_PROGRESS_TYPES: &[&str] = &[
    "agent_progress",
    "bash_progress",
    "compact_progress",
    "hook_progress",
    "mcp_progress",
    "powershell_progress",
    "query_update",
    "repl_progress",
    "search_results_received",
    "skill_progress",
    "waiting_for_task",
    "workflow_progress",
];

pub(crate) const GENERATED_DIRECT_ATTACHMENT_TYPES: &[&str] = &[
    "agent_listing_delta",
    "agent_mention",
    "already_read_file",
    "async_hook_response",
    "auto_mode",
    "auto_mode_exit",
    "bagel_console",
    "budget_usd",
    "command_permissions",
    "compact_file_reference",
    "compaction_reminder",
    "companion_intro",
    "context_efficiency",
    "critical_system_reminder",
    "current_session_memory",
    "date_change",
    "deferred_tools_delta",
    "diagnostics",
    "directory",
    "dynamic_skill",
    "edited_image_file",
    "edited_text_file",
    "file",
    "hook_additional_context",
    "hook_blocking_error",
    "hook_cancelled",
    "hook_error_during_execution",
    "hook_non_blocking_error",
    "hook_permission_decision",
    "hook_stopped_continuation",
    "hook_success",
    "hook_system_message",
    "invoked_skills",
    "max_turns_reached",
    "mcp_instructions_delta",
    "mcp_resource",
    "nested_memory",
    "opened_file_in_ide",
    "output_style",
    "output_token_usage",
    "pdf_reference",
    "plan_file_reference",
    "plan_mode",
    "plan_mode_exit",
    "plan_mode_reentry",
    "queued_command",
    "relevant_memories",
    "selected_lines_in_ide",
    "skill_discovery",
    "skill_listing",
    "structured_output",
    "task_reminder",
    "task_status",
    "team_context",
    "teammate_mailbox",
    "teammate_shutdown_batch",
    "todo_reminder",
    "token_usage",
    "ultrathink_effort",
    "verify_plan_reminder",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_STREAM_EVENT_TYPES: &[&str] = &[
    "content_block_delta",
    "content_block_start",
    "content_block_stop",
    "error",
    "message_delta",
    "message_start",
    "message_stop",
    "ping",
    "sources",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_ASSISTANT_CONTENT_BLOCK_TYPES: &[&str] = &[
    "bash_code_execution_tool_result",
    "code_execution_tool_result",
    "compaction",
    "container_upload",
    "mcp_tool_result",
    "mcp_tool_use",
    "redacted_thinking",
    "server_tool_use",
    "text",
    "text_editor_code_execution_tool_result",
    "thinking",
    "tool_search_tool_result",
    "tool_use",
    "web_fetch_tool_result",
    "web_search_tool_result",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_USER_CONTENT_BLOCK_TYPES: &[&str] = &[
    "bash_code_execution_tool_result",
    "code_execution_tool_result",
    "compaction",
    "container_upload",
    "document",
    "image",
    "mcp_tool_result",
    "mcp_tool_use",
    "redacted_thinking",
    "server_tool_use",
    "text",
    "text_editor_code_execution_tool_result",
    "thinking",
    "tool_result",
    "tool_search_tool_result",
    "tool_use",
    "web_fetch_tool_result",
    "web_search_tool_result",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_SDK_MESSAGE_TYPES: &[&str] = &[
    "assistant",
    "auth_status",
    "prompt_suggestion",
    "rate_limit_event",
    "result",
    "stream_event",
    "system",
    "tool_progress",
    "tool_use_summary",
    "user",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_SDK_SYSTEM_SUBTYPES: &[&str] = &[
    "api_retry",
    "compact_boundary",
    "elicitation_complete",
    "files_persisted",
    "hook_progress",
    "hook_response",
    "hook_started",
    "init",
    "local_command_output",
    "session_state_changed",
    "status",
    "task_notification",
    "task_progress",
    "task_started",
];

pub(crate) const GENERATED_STDOUT_SYSTEM_SUBTYPES: &[&str] = &[
    "api_retry",
    "compact_boundary",
    "elicitation_complete",
    "files_persisted",
    "hook_progress",
    "hook_response",
    "hook_started",
    "init",
    "local_command_output",
    "post_turn_summary",
    "session_state_changed",
    "status",
    "task_notification",
    "task_progress",
    "task_started",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_SDK_RESULT_SUBTYPES: &[&str] = &[
    "error_during_execution",
    "error_max_budget_usd",
    "error_max_structured_output_retries",
    "error_max_turns",
    "success",
];

pub(crate) const GENERATED_CONTROL_REQUEST_SUBTYPES: &[&str] = &[
    "apply_flag_settings",
    "can_use_tool",
    "cancel_async_message",
    "elicitation",
    "get_context_usage",
    "get_settings",
    "hook_callback",
    "initialize",
    "interrupt",
    "mcp_message",
    "mcp_reconnect",
    "mcp_set_servers",
    "mcp_status",
    "mcp_toggle",
    "reload_plugins",
    "rewind_files",
    "seed_read_state",
    "set_max_thinking_tokens",
    "set_model",
    "set_permission_mode",
    "stop_task",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_STDOUT_MESSAGE_TYPES: &[&str] = &[
    "assistant",
    "auth_status",
    "control_cancel_request",
    "control_request",
    "control_response",
    "keep_alive",
    "prompt_suggestion",
    "rate_limit_event",
    "result",
    "stream_event",
    "streamlined_text",
    "streamlined_tool_use_summary",
    "system",
    "tool_progress",
    "tool_use_summary",
    "user",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_STDIN_MESSAGE_TYPES: &[&str] = &[
    "control_request",
    "control_response",
    "keep_alive",
    "update_environment_variables",
    "user",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_PRIVATE_RUNTIME_ACTION_KINDS: &[&str] = &[
    "bug_report_submit",
    "health_snapshot",
    "model.account.consent",
    "model.account.login_cancel",
    "model.account.login_poll",
    "model.account.login_start",
    "model.account.remove",
    "model.account.runtime_ensure",
    "model.account.runtime_stop",
    "model.account.snapshot",
    "model.custom.add",
    "model.custom.list",
    "model.custom.remove",
    "model.custom.test_draft",
    "model.custom.test_saved",
    "model.custom.toggle",
    "model.custom.update",
    "model.local.byo_add",
    "model.local.byo_remove",
    "model.local.download_cancel",
    "model.local.download_progress",
    "model.local.download_start",
    "model.local.install_remove",
    "model.local.server_start",
    "model.local.server_status",
    "model.local.server_stop",
    "model.local.snapshot",
    "plugin_install",
    "plugin_inventory_read",
    "plugin_marketplace_add",
    "plugin_marketplace_catalog_read",
    "plugin_marketplace_inventory_read",
    "plugin_marketplace_remove",
    "plugin_marketplace_set_auto_update",
    "plugin_marketplace_update",
    "plugin_set_enabled",
    "plugin_uninstall",
    "plugin_update",
    "plugin_validate",
    "retained.brief.toggle",
    "retained.color.apply",
    "retained.identity.snapshot",
    "retained.rename.apply",
    "retained.vim.toggle",
    "usage_read",
    "usage_set_five_hour_continue",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_PRIVATE_RUNTIME_RESULT_KINDS: &[&str] = &[
    "bug_report_submitted",
    "bug_report_unconfirmed",
    "health_snapshot",
    "model.account.consent",
    "model.account.login_cancel",
    "model.account.login_poll",
    "model.account.login_start",
    "model.account.remove",
    "model.account.runtime",
    "model.account.snapshot",
    "model.custom.list",
    "model.custom.test",
    "model.local.byo_add",
    "model.local.byo_remove",
    "model.local.download",
    "model.local.install_remove",
    "model.local.server",
    "model.local.snapshot",
    "plugin_enabled_state_updated",
    "plugin_installed",
    "plugin_inventory_snapshot",
    "plugin_marketplace_added",
    "plugin_marketplace_auto_update_updated",
    "plugin_marketplace_catalog_snapshot",
    "plugin_marketplace_inventory_snapshot",
    "plugin_marketplace_removed",
    "plugin_marketplace_updated",
    "plugin_uninstalled",
    "plugin_updated",
    "plugin_validation_result",
    "retained.brief.updated",
    "retained.color.updated",
    "retained.identity.snapshot",
    "retained.rename.updated",
    "retained.vim.updated",
    "retained_command_error",
    "runtime_action_error",
    "usage_five_hour_continue_updated",
    "usage_plugin_error",
    "usage_snapshot",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_PRIVATE_SETUP_REQUEST_ROUTES: &[&str] = &[
    "kind=api_key_approval|stage=-|phase=-",
    "kind=auto_mode_opt_in|stage=-|phase=-",
    "kind=bypass_permissions_consent|stage=-|phase=-",
    "kind=development_channels|stage=-|phase=-",
    "kind=external_crabcode_md|stage=-|phase=-",
    "kind=grove_terms|stage=-|phase=-",
    "kind=mcp_server_approval|stage=-|phase=-",
    "kind=onboarding|stage=language|phase=-",
    "kind=onboarding|stage=oauth|phase=browser_open_failed",
    "kind=onboarding|stage=oauth|phase=browser_url",
    "kind=onboarding|stage=oauth|phase=custom_api_key",
    "kind=onboarding|stage=oauth|phase=custom_base_url",
    "kind=onboarding|stage=oauth|phase=custom_model_id",
    "kind=onboarding|stage=oauth|phase=custom_provider",
    "kind=onboarding|stage=oauth|phase=error",
    "kind=onboarding|stage=oauth|phase=platform_setup",
    "kind=onboarding|stage=oauth|phase=select_method",
    "kind=onboarding|stage=oauth|phase=success",
    "kind=onboarding|stage=preflight|phase=-",
    "kind=onboarding|stage=security|phase=-",
    "kind=onboarding|stage=terminal|phase=-",
    "kind=onboarding|stage=theme|phase=-",
    "kind=renderer_context|stage=-|phase=-",
    "kind=renderer_scroll_speed|stage=-|phase=-",
    "kind=session_picker|stage=-|phase=catalog_chunk",
    "kind=session_picker|stage=-|phase=catalog_show",
    "kind=session_picker|stage=-|phase=catalog_start",
    "kind=session_picker|stage=-|phase=cross_project",
    "kind=session_picker|stage=-|phase=loading",
    "kind=session_picker|stage=-|phase=preview_complete",
    "kind=session_picker|stage=-|phase=preview_failed",
    "kind=session_picker|stage=-|phase=preview_message_chunk",
    "kind=session_picker|stage=-|phase=preview_start",
    "kind=session_picker|stage=-|phase=resolved",
    "kind=workspace_trust|stage=-|phase=-",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_PRIVATE_SETUP_RESPONSE_ROUTES: &[&str] = &[
    "kind=api_key_approval|stage=-|phase=-",
    "kind=auto_mode_opt_in|stage=-|phase=-",
    "kind=bypass_permissions_consent|stage=-|phase=-",
    "kind=development_channels|stage=-|phase=-",
    "kind=external_crabcode_md|stage=-|phase=-",
    "kind=grove_terms|stage=-|phase=-",
    "kind=mcp_server_approval|stage=-|phase=-",
    "kind=onboarding|stage=language|phase=-",
    "kind=onboarding|stage=oauth|phase=browser_open_failed",
    "kind=onboarding|stage=oauth|phase=browser_url",
    "kind=onboarding|stage=oauth|phase=custom_api_key",
    "kind=onboarding|stage=oauth|phase=custom_base_url",
    "kind=onboarding|stage=oauth|phase=custom_model_id",
    "kind=onboarding|stage=oauth|phase=custom_provider",
    "kind=onboarding|stage=oauth|phase=error",
    "kind=onboarding|stage=oauth|phase=platform_setup",
    "kind=onboarding|stage=oauth|phase=select_method",
    "kind=onboarding|stage=oauth|phase=success",
    "kind=onboarding|stage=preflight|phase=-",
    "kind=onboarding|stage=security|phase=-",
    "kind=onboarding|stage=terminal|phase=-",
    "kind=onboarding|stage=theme|phase=-",
    "kind=renderer_context|stage=-|phase=-",
    "kind=renderer_scroll_speed|stage=-|phase=-",
    "kind=session_picker|stage=-|phase=catalog_chunk",
    "kind=session_picker|stage=-|phase=catalog_start",
    "kind=session_picker|stage=-|phase=interaction",
    "kind=session_picker|stage=-|phase=loading",
    "kind=session_picker|stage=-|phase=preview_message_chunk",
    "kind=session_picker|stage=-|phase=preview_start",
    "kind=session_picker|stage=-|phase=resolved",
    "kind=workspace_trust|stage=-|phase=-",
];

#[cfg(test)]
#[allow(dead_code)]
pub(crate) const GENERATED_TS_TO_RUST_MIGRATION_FAMILIES: &[(&str, &str, &str, &str)] = &[
    (
        "query_message_type",
        "src/types/message.ts",
        "Message",
        "crabcode-tui::sdk_runtime -> sdk_projection -> scrollback_projection",
    ),
    (
        "direct_system_subtype",
        "src/types/message.ts",
        "SystemMessage",
        "crabcode-tui::sdk_runtime::DirectSystemSubtype + sdk_projection",
    ),
    (
        "progress_type",
        "src/Tool.ts",
        "Progress",
        "crabcode-tui::sdk_projection progress lifecycle",
    ),
    (
        "attachment_type",
        "src/utils/attachments-types.ts",
        "Attachment",
        "crabcode-tui::sdk_projection attachment disposition partition",
    ),
    (
        "stream_event_type",
        "src/types/api-types.ts",
        "NormalizedAcosmiChatStreamEvent",
        "crabcode-tui::sdk_projection generation-aware stream reducer",
    ),
    (
        "assistant_content_block_type",
        "src/types/api-types.ts",
        "BetaContentBlock",
        "crabcode-tui::sdk_projection::AssistantBlockType",
    ),
    (
        "user_content_block_type",
        "src/types/api-types.ts",
        "BetaContentBlockParam",
        "crabcode-tui::sdk_projection::DirectUserBlockType",
    ),
    (
        "sdk_message_type",
        "src/entrypoints/sdk/coreTypes.generated.ts",
        "SDKMessage",
        "crabcode-tui::sdk_runtime::EnvelopeClass",
    ),
    (
        "sdk_system_subtype",
        "src/entrypoints/sdk/coreTypes.generated.ts",
        "SDKMessage",
        "crabcode-tui::sdk_runtime::SystemSubtype",
    ),
    (
        "stdout_system_subtype",
        "src/entrypoints/sdk/controlTypes.ts",
        "StdoutMessage",
        "crabcode-tui::sdk_runtime::SystemSubtype",
    ),
    (
        "sdk_result_subtype",
        "src/entrypoints/sdk/coreTypes.generated.ts",
        "SDKMessage",
        "crabcode-tui::sdk_runtime correlated result lifecycle",
    ),
    (
        "control_request_subtype",
        "src/entrypoints/sdk/controlTypes.ts",
        "SDKControlRequestInner",
        "crabcode-tui::sdk_runtime reverse-control classifier",
    ),
    (
        "stdout_message_type",
        "src/entrypoints/sdk/controlTypes.ts",
        "StdoutMessage",
        "crabcode-tui::sdk_runtime bounded stdout reader",
    ),
    (
        "stdin_message_type",
        "src/entrypoints/sdk/controlTypes.ts",
        "StdinMessage",
        "crabcode-tui::sdk_runtime bounded outbound writer",
    ),
    (
        "private_runtime_action_kind",
        "src/cli/directTuiRuntimeActions.ts",
        "DirectTuiRuntimeAction",
        "crabcode-tui::sdk_runtime::validate_private_runtime_action",
    ),
    (
        "private_runtime_result_kind",
        "src/cli/directTuiRuntimeActions.ts",
        "DirectTuiRuntimeResult",
        "crabcode-tui::sdk_runtime private result classifier",
    ),
    (
        "private_setup_request_route",
        "src/cli/crabcodeTuiBridgeProtocol.ts",
        "CrabCodeTuiSetupRequest",
        "crabcode-tui::tui_app private setup request router",
    ),
    (
        "private_setup_response_route",
        "src/cli/crabcodeTuiBridgeProtocol.ts",
        "CrabCodeTuiSetupResponse",
        "crabcode-tui::tui_app private setup response encoder",
    ),
];
