// settings.language remains a free-form string for compatibility with existing
// settings surfaces. Resolve it through a strict whitelist before using it in
// any model prompt so transport-neutral helpers do not need to import the full
// system-prompt assembly graph.
const LANGUAGE_DISPLAY_NAME_WHITELIST: Record<string, string> = {
  english: 'English',
  en: 'English',
  spanish: 'Spanish',
  español: 'Spanish',
  espanol: 'Spanish',
  es: 'Spanish',
  french: 'French',
  français: 'French',
  francais: 'French',
  fr: 'French',
  japanese: 'Japanese',
  日本語: 'Japanese',
  ja: 'Japanese',
  german: 'German',
  deutsch: 'German',
  de: 'German',
  portuguese: 'Portuguese',
  português: 'Portuguese',
  portugues: 'Portuguese',
  pt: 'Portuguese',
  italian: 'Italian',
  italiano: 'Italian',
  it: 'Italian',
  korean: 'Korean',
  한국어: 'Korean',
  ko: 'Korean',
  hindi: 'Hindi',
  हिन्दी: 'Hindi',
  हिंदी: 'Hindi',
  hi: 'Hindi',
  indonesian: 'Indonesian',
  'bahasa indonesia': 'Indonesian',
  id: 'Indonesian',
  russian: 'Russian',
  русский: 'Russian',
  ru: 'Russian',
  polish: 'Polish',
  polski: 'Polish',
  pl: 'Polish',
  turkish: 'Turkish',
  türkçe: 'Turkish',
  turkce: 'Turkish',
  tr: 'Turkish',
  dutch: 'Dutch',
  nederlands: 'Dutch',
  nl: 'Dutch',
  ukrainian: 'Ukrainian',
  українська: 'Ukrainian',
  uk: 'Ukrainian',
  greek: 'Greek',
  ελληνικά: 'Greek',
  el: 'Greek',
  czech: 'Czech',
  čeština: 'Czech',
  cestina: 'Czech',
  cs: 'Czech',
  danish: 'Danish',
  dansk: 'Danish',
  da: 'Danish',
  swedish: 'Swedish',
  svenska: 'Swedish',
  sv: 'Swedish',
  norwegian: 'Norwegian',
  norsk: 'Norwegian',
  no: 'Norwegian',
  chinese: 'Chinese',
  中文: 'Chinese',
  简体中文: 'Chinese',
  繁體中文: 'Chinese',
  zh: 'Chinese',
  'zh-cn': 'Chinese',
  'zh-tw': 'Chinese',
  arabic: 'Arabic',
  العربية: 'Arabic',
  ar: 'Arabic',
  vietnamese: 'Vietnamese',
  'tiếng việt': 'Vietnamese',
  tieng_viet: 'Vietnamese',
  vi: 'Vietnamese',
  thai: 'Thai',
  ไทย: 'Thai',
  th: 'Thai',
}

export function sanitizeLanguagePreference(
  raw: string | undefined,
): string | null {
  if (!raw || typeof raw !== 'string') return null
  if (raw.length > 64) return null
  if (/[\n\r\t.,;<>\[\]{}|`!?]/.test(raw)) return null
  const normalized = raw.toLowerCase().trim()
  if (!normalized) return null
  return LANGUAGE_DISPLAY_NAME_WHITELIST[normalized] ?? null
}
